[package]
name = "unm_engine_kugou"
description = "The Kugou engine for UnblockNeteaseMusic."
license = "LGPL-3.0-or-later"
version = "0.3.0-pre.1"
repository = "https://github.com/UnblockNeteaseMusic/server-rust"
readme = "../../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
http = "0.2.7"
serde_json = "1.0.80"
serde = { version = "1.0.137", features = ["derive"] }
reqwest = { version = "0.11.10", features = ["native-tls-vendored"] }
futures = "0.3.21"
unm_engine = { version = "0.3.0-pre.0", path = "../../engine-base" }
unm_request = { version = "0.3.0-pre.0", path = "../../request" }
unm_selector = { version = "0.3.0-pre.0", path = "../../selector" }
unm_types = { version = "0.3.0-pre.0", path = "../../types" }
log = "0.4.16"
concat-string = "1.0.1"

[dev-dependencies]
tokio = { version = "1.18.1", features = ["macros", "rt-multi-thread"] }
unm_test_utils = { path = "../../test-utils" }
