[package]
name = "unm_engine_pyncm"
description = "The PyNCM engine for UnblockNeteaseMusic."
license = "LGPL-3.0-or-later"
version = "0.2.0-pre.2"
repository = "https://github.com/UnblockNeteaseMusic/server-rust"
readme = "../../README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
http = "0.2.6"
serde = { version = "1.0.136", features = ["derive"] }
unm_engine = { version = "0.2.0-pre.1", path = "../../engine-base" }
unm_request = { version = "0.2.0-pre.1", path = "../../request" }
unm_types = { version = "0.2.0-pre.1", path = "../../types" }
url = "2.2.2"
log = "0.4.16"
