[package]
name = "unm_engine_demo"
description = "Demonstrate how engines work in UnblockNeteaseMusic."
license = "LGPL-3.0-or-later"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/UnblockNeteaseMusic/server-rust"
readme = "../README.md"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unm_test_utils = { version = "0.1.0", path = "../test-utils" }
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }
futures = "0.3.21"
unm_types = { version = "0.3.0-pre.0", path = "../types" }
mimalloc = "0.1.29"
unm_api_utils = { version = "0.3.0-pre.0", path = "../api-utils" }
